import numpy as np

def cy_ltrb_to_ltwh(bbox: np.ndarray) -> np.ndarray: ...
def cy_ltwh_to_xywh(bbox: np.ndarray) -> np.ndarray: ...
def cy_xywh_to_ltrb(bbox: np.ndarray) -> np.ndarray: ...
def cy_ltrb_to_xywh(bbox: np.ndarray) -> np.ndarray: ...
def cy_xywh_to_ltwh(bbox: np.ndarray) -> np.ndarray: ...
def cy_ltwh_to_ltrb(bbox: np.ndarray) -> np.ndarray: ...

#
def cy_bbox_overlaps_iou(boxes: np.ndarray, query_boxes: np.ndarray) -> np.ndarray: ...
def cy_bbox_overlaps_giou(boxes: np.ndarray, query_boxes: np.ndarray) -> np.ndarray: ...

#
def cy_bbox_union_area(boxes: np.ndarray, query_boxes: np.ndarray) -> np.ndarray: ...
def cy_bbox_overlaps_area(boxes: np.ndarray, query_boxes: np.ndarray) -> np.ndarray: ...
def cy_bbox_overlaps_flag(boxes: np.ndarray, query_boxes: np.ndarray) -> np.ndarray: ...
